// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvBWet2PRU93bNzE2CpyzNnGCZTxcjbc',
    appId: '1:28904262797:web:e409df7c81c2376d5ca6c4',
    messagingSenderId: '28904262797',
    projectId: 'my-firebase-project-a7f89',
    authDomain: 'my-firebase-project-a7f89.firebaseapp.com',
    storageBucket: 'my-firebase-project-a7f89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX4gMeAZzl6Izthd7C7y4GpdYpIrGzw5Q',
    appId: '1:28904262797:android:b71e637ddd2824395ca6c4',
    messagingSenderId: '28904262797',
    projectId: 'my-firebase-project-a7f89',
    storageBucket: 'my-firebase-project-a7f89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSAwqPkOJ17h4pZWeJN7EX7tAlw8BcTRI',
    appId: '1:28904262797:ios:8b20b99a7f5930975ca6c4',
    messagingSenderId: '28904262797',
    projectId: 'my-firebase-project-a7f89',
    storageBucket: 'my-firebase-project-a7f89.appspot.com',
    iosClientId: '28904262797-k1su9nbgfdcclrefn77p4487ndlmqaa6.apps.googleusercontent.com',
    iosBundleId: 'com.example.savegreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSAwqPkOJ17h4pZWeJN7EX7tAlw8BcTRI',
    appId: '1:28904262797:ios:8b20b99a7f5930975ca6c4',
    messagingSenderId: '28904262797',
    projectId: 'my-firebase-project-a7f89',
    storageBucket: 'my-firebase-project-a7f89.appspot.com',
    iosClientId: '28904262797-k1su9nbgfdcclrefn77p4487ndlmqaa6.apps.googleusercontent.com',
    iosBundleId: 'com.example.savegreen',
  );
}
